### ISSUE TITLE
Fichie PBF / tuiles vectorielles : filtre des bâtiments selon statut

### ISSUE THREAD

**Issue by pe-beta** [fab-geocommuns/RNB-coeur#158]
Actuellement les bâtiments sont affichés quel que soit leur statut.
On veut qu’il y ait uniquement les bâtiments de l’affichage par défaut, comme sur l’API de recherche.

**Comment by fchabouis** [comment]
Effectivement on dirait que pour l'instant on affiche tout https://github.com/fab-geocommuns/RNB-coeur/blob/79536ba3dce705684baad5179d631337e2a6d717/app/batid/services/vector_tiles.py#L80
