### ISSUE TITLE
Python requirements available upgrades

### ISSUE THREAD

**Issue by rmaziere** [fab-geocommuns/RNB-coeur#407]
# Liste des mises à jour de paquets disponibles

## Sur l'ensemble des paquets présents dans `requirements.txt`

| Package | Current version | Latest version | Release date |
|---|---|---|---|
| amqp | 5.1.1 | 5.2.0 | 2023-11-06 |
| anyio | 4.0.0 | 4.4.0 | 2024-05-26 |
| arrow | 1.2.3 | 1.3.0 | 2023-09-30 |
| asgiref | 3.6.0 | 3.8.1 | 2024-03-22 |
| asttokens | 2.4.0 | 2.4.1 | 2023-10-26 |
| async-timeout | 4.0.2 | 4.0.3 | 2023-08-10 |
| attrs | 22.2.0 | 23.2.0 | 2023-12-31 |
| beautifulsoup4 | 4.12.2 | 4.12.3 | 2024-01-17 |
| billiard | 3.6.4.0 | 4.2.0 | 2023-11-06 |
| bleach | 6.0.0 | 6.1.0 | 2023-10-06 |
| boto3 | 1.34.16 | 1.34.119 | 2024-06-04 |
| botocore | 1.34.84 | 1.34.119 | 2024-06-04 |
| Brotli | 1.0.9 | 1.1.0 | 2023-09-07 |
| celery | 5.2.7 | 5.4.0 | 2024-04-17 |
| certifi | 2023.7.22 | 2024.6.2 | 2024-06-02 |
| cffi | 1.15.1 | 1.16.0 | 2023-09-28 |
| charset-normalizer | 3.1.0 | 3.3.2 | 2023-11-01 |
| click | 8.1.3 | 8.1.7 | 2023-08-17 |
| click-didyoumean | 0.3.0 | 0.3.1 | 2024-03-24 |
| click-repl | 0.2.0 | 0.3.0 | 2023-06-15 |
| comm | 0.1.4 | 0.2.2 | 2024-03-12 |
| contourpy | 1.0.7 | 1.2.1 | 2024-04-02 |
| cryptography | 42.0.4 | 42.0.8 | 2024-06-04 |
| cycler | 0.11.0 | 0.12.1 | 2023-10-07 |
| debugpy | 1.8.0 | 1.8.1 | 2024-02-08 |
| Django | 4.1.13 | 5.0.6 | 2024-05-07 |
| django-cors-headers | 3.14.0 | 4.3.1 | 2023-11-14 |
| django-filter | 22.1 | 24.2 | 2024-03-27 |
| django-revproxy | 0.11.0 | 0.12.0 | 2023-10-20 |
| django_debug_toolbar | 3.8.1 | 4.4.2 | 2024-05-27 |
| djangorestframework | 3.14.0 | 3.15.1 | 2024-03-22 |
| exceptiongroup | 1.1.3 | 1.2.1 | 2024-04-18 |
| executing | 1.2.0 | 2.0.1 | 2023-10-29 |
| fastjsonschema | 2.18.0 | 2.19.1 | 2023-12-28 |
| Fiona | 1.9.1 | 1.9.6 | 2024-03-08 |
| fonttools | 4.43.0 | 4.53.0 | 2024-05-31 |
| geopy | 2.4.0 | 2.4.1 | 2023-11-23 |
| gunicorn | 20.1.0 | 22.0.0 | 2024-04-16 |
| idna | 3.4 | 3.7 | 2024-04-11 |
| inflate64 | 0.3.1 | 1.0.0 | 2023-11-05 |
| ipykernel | 6.25.2 | 6.29.4 | 2024-03-27 |
| Jinja2 | 3.1.3 | 3.1.4 | 2024-05-05 |
| jsonschema | 4.19.1 | 4.22.0 | 2024-04-30 |
| jsonschema-specifications | 2023.7.1 | 2023.12.1 | 2023-12-25 |
| jupyter-events | 0.7.0 | 0.10.0 | 2024-03-18 |
| jupyter_client | 7.4.9 | 8.6.2 | 2024-05-23 |
| jupyter_core | 5.3.1 | 5.7.2 | 2024-03-12 |
| jupyter_server | 2.7.3 | 2.14.1 | 2024-05-31 |
| jupyter_server_terminals | 0.4.4 | 0.5.3 | 2024-03-12 |
| jupyterlab-pygments | 0.2.2 | 0.3.0 | 2023-11-23 |
| kiwisolver | 1.4.4 | 1.4.5 | 2023-08-24 |
| kombu | 5.2.4 | 5.3.7 | 2024-04-11 |
| Markdown | 3.4.1 | 3.6 | 2024-03-14 |
| MarkupSafe | 2.1.3 | 2.1.5 | 2024-02-02 |
| matplotlib | 3.7.1 | 3.9.0 | 2024-05-15 |
| matplotlib-inline | 0.1.6 | 0.1.7 | 2024-04-15 |
| mistune | 3.0.1 | 3.0.2 | 2023-09-29 |
| moto | 5.0.2 | 5.0.9 | 2024-05-30 |
| munch | 2.5.0 | 4.0.0 | 2023-07-01 |
| nbclassic | 1.0.0 | 1.1.0 | 2024-05-24 |
| nbclient | 0.8.0 | 0.10.0 | 2024-03-13 |
| nbconvert | 7.8.0 | 7.16.4 | 2024-04-29 |
| nbformat | 5.9.2 | 5.10.4 | 2024-04-04 |
| nest-asyncio | 1.5.8 | 1.6.0 | 2024-01-21 |
| notebook | 6.5.5 | 7.2.0 | 2024-05-16 |
| notebook_shim | 0.2.3 | 0.2.4 | 2024-02-14 |
| numpy | 1.24.2 | 1.26.4 | 2024-02-05 |
| overrides | 7.4.0 | 7.7.0 | 2024-01-27 |
| packaging | 23.0 | 24.0 | 2024-03-10 |
| pandas | 1.5.3 | 2.2.2 | 2024-04-10 |
| pandocfilters | 1.5.0 | 1.5.1 | 2024-01-18 |
| parso | 0.8.3 | 0.8.4 | 2024-04-05 |
| pexpect | 4.8.0 | 4.9.0 | 2023-11-25 |
| pillow | 10.2.0 | 10.3.0 | 2024-04-01 |
| platformdirs | 3.10.0 | 4.2.2 | 2024-05-15 |
| prometheus-client | 0.17.1 | 0.20.0 | 2024-02-14 |
| prompt-toolkit | 3.0.38 | 3.0.46 | 2024-06-04 |
| psutil | 5.9.4 | 5.9.8 | 2024-01-19 |
| psycopg2 | 2.9.5 | 2.9.9 | 2023-10-03 |
| py-partiql-parser | 0.5.1 | 0.5.5 | 2024-05-11 |
| py7zr | 0.20.4 | 0.21.0 | 2024-03-02 |
| pybcj | 1.0.1 | 1.0.2 | 2023-11-05 |
| pycparser | 2.21 | 2.22 | 2024-03-30 |
| pycryptodomex | 3.19.1 | 3.20.0 | 2024-01-10 |
| Pygments | 2.16.1 | 2.18.0 | 2024-05-04 |
| pyparsing | 3.0.9 | 3.1.2 | 2024-03-06 |
| pyppmd | 1.0.0 | 1.1.0 | 2023-11-05 |
| pyproj | 3.4.1 | 3.6.1 | 2023-09-21 |
| python-dateutil | 2.8.2 | 2.9.0 | 2024-03-01 |
| PyYAML | 6.0 | 6.0.1 | 2023-07-17 |
| pyzmq | 24.0.1 | 26.0.3 | 2024-05-01 |
| pyzstd | 0.15.4 | 0.16.0 | 2024-05-20 |
| redis | 4.5.4 | 5.0.4 | 2024-04-23 |
| referencing | 0.30.2 | 0.35.1 | 2024-05-01 |
| requests | 2.31.0 | 2.32.3 | 2024-05-29 |
| rpds-py | 0.10.3 | 0.18.1 | 2024-05-06 |
| Send2Trash | 1.8.2 | 1.8.3 | 2024-04-07 |
| sentry-sdk | 1.19.1 | 2.4.0 | 2024-06-04 |
| shapely | 2.0.3 | 2.0.4 | 2024-04-16 |
| sniffio | 1.3.0 | 1.3.1 | 2024-02-25 |
| sqlparse | 0.4.4 | 0.5.0 | 2024-04-13 |
| stack-data | 0.6.2 | 0.6.3 | 2023-09-30 |
| terminado | 0.17.1 | 0.18.1 | 2024-03-12 |
| texttable | 1.6.7 | 1.7.0 | 2023-10-03 |
| tinycss2 | 1.2.1 | 1.3.0 | 2024-04-23 |
| tornado | 6.3.3 | 6.4 | 2023-11-29 |
| traitlets | 5.9.0 | 5.14.3 | 2024-04-19 |
| urllib3 | 1.26.18 | 2.2.1 | 2024-02-18 |
| vine | 5.0.0 | 5.1.0 | 2023-11-05 |
| watchdog | 3.0.0 | 4.0.1 | 2024-05-23 |
| wcwidth | 0.2.6 | 0.2.13 | 2024-01-06 |
| websocket-client | 1.5.1 | 1.8.0 | 2024-04-23 |
| Werkzeug | 3.0.2 | 3.0.3 | 2024-05-05 |
| whitenoise | 6.4.0 | 6.6.0 | 2023-10-11 |
| drf-spectacular | 0.27.1 | 0.27.2 | 2024-04-01 |

## Seulement ceux dont la dernière version a été publiée l'année dernière

| Package | Current version | Latest version | Release date |
|---|---|---|---|
| click-repl | 0.2.0 | 0.3.0 | 2023-06-15 |
| munch | 2.5.0 | 4.0.0 | 2023-07-01 |
| PyYAML | 6.0 | 6.0.1 | 2023-07-17 |
| async-timeout | 4.0.2 | 4.0.3 | 2023-08-10 |
| click | 8.1.3 | 8.1.7 | 2023-08-17 |
| kiwisolver | 1.4.4 | 1.4.5 | 2023-08-24 |
| Brotli | 1.0.9 | 1.1.0 | 2023-09-07 |
| pyproj | 3.4.1 | 3.6.1 | 2023-09-21 |
| cffi | 1.15.1 | 1.16.0 | 2023-09-28 |
| mistune | 3.0.1 | 3.0.2 | 2023-09-29 |
| arrow | 1.2.3 | 1.3.0 | 2023-09-30 |
| stack-data | 0.6.2 | 0.6.3 | 2023-09-30 |
| texttable | 1.6.7 | 1.7.0 | 2023-10-03 |
| psycopg2 | 2.9.5 | 2.9.9 | 2023-10-03 |
| bleach | 6.0.0 | 6.1.0 | 2023-10-06 |
| cycler | 0.11.0 | 0.12.1 | 2023-10-07 |
| whitenoise | 6.4.0 | 6.6.0 | 2023-10-11 |
| django-revproxy | 0.11.0 | 0.12.0 | 2023-10-20 |
| asttokens | 2.4.0 | 2.4.1 | 2023-10-26 |
| executing | 1.2.0 | 2.0.1 | 2023-10-29 |
| charset-normalizer | 3.1.0 | 3.3.2 | 2023-11-01 |
| inflate64 | 0.3.1 | 1.0.0 | 2023-11-05 |
| pybcj | 1.0.1 | 1.0.2 | 2023-11-05 |
| pyppmd | 1.0.0 | 1.1.0 | 2023-11-05 |
| vine | 5.0.0 | 5.1.0 | 2023-11-05 |
| billiard | 3.6.4.0 | 4.2.0 | 2023-11-06 |
| amqp | 5.1.1 | 5.2.0 | 2023-11-06 |
| django-cors-headers | 3.14.0 | 4.3.1 | 2023-11-14 |
| geopy | 2.4.0 | 2.4.1 | 2023-11-23 |
| jupyterlab-pygments | 0.2.2 | 0.3.0 | 2023-11-23 |
| pexpect | 4.8.0 | 4.9.0 | 2023-11-25 |
| jsonschema-specifications | 2023.7.1 | 2023.12.1 | 2023-12-25 |
| fastjsonschema | 2.18.0 | 2.19.1 | 2023-12-28 |
| tornado | 6.3.3 | 6.4 | 2023-11-29 |
| attrs | 22.2.0 | 23.2.0 | 2023-12-31 |

## Seulement ceux qui ont changé de version majeure

| Package | Current version | Latest version | Release date |
|---|---|---|---|
| attrs | 22.2.0 | 23.2.0 | 2023-12-31 |
| billiard | 3.6.4.0 | 4.2.0 | 2023-11-06 |
| certifi | 2023.7.22 | 2024.6.2 | 2024-06-02 |
| Django | 4.1.13 | 5.0.6 | 2024-05-07 |
| django-cors-headers | 3.14.0 | 4.3.1 | 2023-11-14 |
| django-filter | 22.1 | 24.2 | 2024-03-27 |
| django_debug_toolbar | 3.8.1 | 4.4.2 | 2024-05-27 |
| executing | 1.2.0 | 2.0.1 | 2023-10-29 |
| gunicorn | 20.1.0 | 22.0.0 | 2024-04-16 |
| jupyter_client | 7.4.9 | 8.6.2 | 2024-05-23 |
| munch | 2.5.0 | 4.0.0 | 2023-07-01 |
| notebook | 6.5.5 | 7.2.0 | 2024-05-16 |
| packaging | 23.0 | 24.0 | 2024-03-10 |
| pandas | 1.5.3 | 2.2.2 | 2024-04-10 |
| platformdirs | 3.10.0 | 4.2.2 | 2024-05-15 |
| pyzmq | 24.0.1 | 26.0.3 | 2024-05-01 |
| redis | 4.5.4 | 5.0.4 | 2024-04-23 |
| sentry-sdk | 1.19.1 | 2.4.0 | 2024-06-04 |
| urllib3 | 1.26.18 | 2.2.1 | 2024-02-18 |
| watchdog | 3.0.0 | 4.0.1 | 2024-05-23 |

**Comment by rmaziere** [comment]
Dependabot alerts
===

# gunicorn 20.1.0 => 22.0.0
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/36

# Werkzeug 3.0.2 => 3.0.3
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/37
PR #408 

# sqlparse 0.4.4 => 0.5.0
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/34
PR #409 

# requests 2.31.0 => 2.32.0
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/39
PR #410 

# Jinja2 3.1.3 => 3.1.4
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/38
PR #411

# idna 3.4 => 3.7
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/33
PR #412 

# pillow 10.2.0 => 10.3.0
https://github.com/fab-geocommuns/RNB-coeur/security/dependabot/32
PR #413

**Comment by rmaziere** [comment]
Django
===

Version actuellement utilisée : 4.1.13 qui est EOL depuis décembre 2023.
[Versions supportées](https://www.djangoproject.com/download/#supported-versions)
Il semble intéressant de passer à la 4.2 qui est LTS, EOL en avril 2026.

[Releases notes](https://docs.djangoproject.com/en/4.2/releases/)

[Django 4.2 release notes](https://docs.djangoproject.com/en/4.2/releases/4.2/)
Dont le support de Psycopg3 (actuellement utilisation de Psycopg2)

[How to upgrade](https://docs.djangoproject.com/fr/5.0/howto/upgrade-version/)

**Comment by fchabouis** [comment]
beaucoup de packages ont été mis à jour cet été.
